### ISSUE TITLE
No scrolling in exceptions list

### ISSUE THREAD

**Issue by liam-d99** [kianzarrin/HideTMPECrosswalks#16]
Not sure if you would rather have this in the workshop comments. Anyway...

I have quite a lot of roads installed on the workshop. The effect of this is that I cannot make exceptions for some roads. The list does not have a scrollbar for this. Maybe a scrollbar could be added, or the type of form could be changed alltogether.

Thanks for an amazing mod.
- Liam

**Comment by kianzarrin** [comment]
We recently discovered how to attach a scrollbar in the modding community. so I will add a scrollbar. it might take a while I have a massive backlog of mods and fire fighting.

meanwhile I think you can locate the text file in which these roads are stored and add them manually:
`HideCrosswalks.Config.txt`

**Comment by kianzarrin** [comment]
@liam-d99 I am now working on this feature.
I didn't know there are people using it actually.
I am wondering how should I populate the list?
currently, I group all the different elevations/decorations of the road into one. (decoration=tree/grass)
should I display a user-friendly name or should I display a low-level name?  low-level name has no risk of name conflict.

**Comment by kianzarrin** [comment]
did't manage to make the scrolbar visible. but the list popup box IS scrollable using mousewheel.
![image](https://user-images.githubusercontent.com/26344691/95009808-820b3680-062d-11eb-97de-f03cf3831511.png)

**Comment by kianzarrin** [comment]
published to hide crossings experimental workshop

**Comment by liam-d99** [comment]
Thanks so much for the quick response and fix! I'll definitely try it later today. I'll look into the way its formatted then. I use it for multiple roads that are supposed to work together to make a turn lane In a larger avenue. On the nodes where it changes road types pedestrians cross the road. Here I want to disable the crossing, but if I do that without the exception turned on it messes with the lane markings. It might be possible to automate the mod to ignore these junctions, but I think this feature works for what I want to accomplish. (will add screenshots and links to the road later)
