### ISSUE TITLE
Error in output log

### ISSUE THREAD

**Issue by t1a2l** [kianzarrin/HideTMPECrosswalks#7]
HideTMPECrosswalks patches Reverted.
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

NullReferenceException
  at (wrapper managed-to-native) UnityEngine.Component:get_transform ()
  at BuildingThemes.BuildingVariationManager.Reset () [0x00000] in <filename unknown>:0 
  at BuildingThemes.LoadingExtension.OnReleased () [0x00000] in <filename unknown>:0 
  at LoadingWrapper.OnLoadingExtensionsReleased () [0x00000] in <filename unknown>:0 
UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
LoadingWrapper:OnLoadingExtensionsReleased()
LoadingWrapper:Release()
LoadingManager:ReleaseRelay()
LoadingManager:OnDestroy()

**Comment by kianzarrin** [comment]
@t1a2l can you please provide more context? What other mods you have? Is it happening while exiting the game? Does it happen if you only have My mod and TMPE?

**Comment by originalfoo** [comment]
Building Themes mod is unreliable, it's constantly showing up in support log files

**Comment by t1a2l** [comment]
@kianzarrin - Hey, sorry for the late replay, it just show at the end of the output log. Also some workshop roads suddenly don't have crosswalks by default when placing them down.

**Comment by kianzarrin** [comment]
Does it happen without the building themes mod?
What roads have no crossings?
@t1a2l you need to give me more info there's no way I can debug this line this

**Comment by t1a2l** [comment]
Once I disabled theme manager the crosswalk returned

**Comment by originalfoo** [comment]
By "theme manager" do you mean the Building Themes mod?

**Comment by t1a2l** [comment]
yes
